language: php
php:
  - '5.5'
  - '5.6'
  - '7.1'

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
