language: php
php:
  - '5.5'
  - '5.6'
  - '7.1'

before_script:
  - composer install --no-dev

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls -v
